#! /bin/bash

echo 'set term png size 800,600' > gnuplotScript.tmp

for i in $1*.dat
do
  filename=`echo $i | sed 's/dat/png/'`

  echo "set output '$filename'" >> gnuplotScript.tmp
  echo "set xrange [0:$2]">> gnuplotScript.tmp
  echo "set yrange [0:$2]" >> gnuplotScript.tmp
  echo "set zrange [-1.5:1.5]" >> gnuplotScript.tmp
  echo "set key off" >> gnuplotScript.tmp
  echo "set hidden3d" >> gnuplotScript.tmp
  echo "splot '$i' matrix with lines" >> gnuplotScript.tmp
  echo "reset" >> gnuplotScript.tmp
done

gnuplot gnuplotScript.tmp

rm gnuplotScript.tmp

convert -delay 10 -loop 0 $1*.png $3

rm -r $1*.png
