#! /bin/bash

echo 'set terminal png' > gnuplotScript.tmp

mkdir -p ani-tmp

for i in $1*.dat
do
  filename=`echo $i | sed 's/dat/png/'`

  echo "set output '$filename'" >> gnuplotScript.tmp
  echo "set xrange [0:$2]" >> gnuplotScript.tmp
#  echo "set yrange [-0.1:1.1]" >> gnuplotScript.tmp
  echo "plot '$i' with lines" >> gnuplotScript.tmp
  echo "reset" >> gnuplotScript.tmp
done

gnuplot gnuplotScript.tmp

rm gnuplotScript.tmp

convert -delay 10 -loop 0 $1*.png $3

rm -r $1*.png
