#! /bin/bash

touch gnuplotScript.tmp

echo "set term svg" >> gnuplotScript.tmp
echo "set output \"$3\"" >> gnuplotScript.tmp
echo "set xrange [0:$2]" >> gnuplotScript.tmp
echo "set object 1 rect from screen 0,0,0 to screen 1,1,0 behind" >> gnuplotScript.tmp
echo "set object 1 rect fc rgb \"white\" fillstyle solid 1.0" >> gnuplotScript.tmp
echo "plot '$1' matrix with lines" >> gnuplotScript.tmp

gnuplot gnuplotScript.tmp

rm gnuplotScript.tmp
