#! /bin/bash

echo 'set terminal png' >> my_plot.tmp

for i in *.dat
do
  filename=`echo $i | sed 's/dat/png/'`
  
  echo "set output '$filename'" >> my_plot.tmp
  echo "set xrange [0:512]" >> my_plot.tmp
  echo "set yrange [-0.1:1.1]" >> my_plot.tmp
  echo "plot '$i' matrix  with lines" >> my_plot.tmp
done

gnuplot my_plot.tmp

rm my_plot.tmp

convert -delay 10 -loop 0 *.png ani.gif

rm *.png

